name: ecpath
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.20
  - cudatoolkit=11.8.0
  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib=3.9.2
  - opencv=4.7.0
  - pillow=10.4.0
  - pytorch=2.5.0
  - torchaudio=2.5.0
  - torchvision=0.15.2
  - ipykernel=6.29.5
  - jupyterlab=4.2.5
  - openslide-python=1.3.1
  - pip=24.2
  - pip:
    - huggingface-hub==0.26.1
    - timm==1.0.11
    - scipy==1.13.1
    - spams==2.6.5.4
    - sympy==1.13.1
    - fsspec==2024.10.0
    - safetensors==0.4.5
    - tqdm==4.66.5
    